// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'api/network.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1855335011;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'weft_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiEngineBridgeVersion();

  BigInt crateApiEngineEngineStartSession();

  SessionStatusView crateApiEngineEngineStatus();

  void crateApiEngineEngineStopSession();

  Future<void> crateApiSimpleInitApp();

  void crateApiNetworkNetworkApproveTransmit({required String deviceId});

  void crateApiNetworkNetworkDenyTransmit({required String deviceId});

  void crateApiNetworkNetworkDjTransmit({required bool active});

  Stream<NetworkEventView> crateApiNetworkNetworkEvents();

  List<String> crateApiNetworkNetworkInputDevices();

  MediaStatsView? crateApiNetworkNetworkMediaStats();

  void crateApiNetworkNetworkReleaseTransmit();

  void crateApiNetworkNetworkRequestTransmit();

  void crateApiNetworkNetworkRespondToCede({required bool cede});

  void crateApiNetworkNetworkStart({required String deviceName});

  void crateApiNetworkNetworkStartCapture({String? deviceName});

  void crateApiNetworkNetworkStartWith({
    required String deviceName,
    required bool enableAudio,
    required bool dj,
  });

  NetworkStatusView crateApiNetworkNetworkStatus();

  void crateApiNetworkNetworkStop();

  void crateApiNetworkNetworkStopCapture();

  void crateApiNetworkNetworkTransmitFile({required String path});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiEngineBridgeVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineBridgeVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineBridgeVersionConstMeta =>
      const TaskConstMeta(debugName: "bridge_version", argNames: []);

  @override
  BigInt crateApiEngineEngineStartSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineStartSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineStartSessionConstMeta =>
      const TaskConstMeta(debugName: "engine_start_session", argNames: []);

  @override
  SessionStatusView crateApiEngineEngineStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_status_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineStatusConstMeta =>
      const TaskConstMeta(debugName: "engine_status", argNames: []);

  @override
  void crateApiEngineEngineStopSession() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineEngineStopSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEngineStopSessionConstMeta =>
      const TaskConstMeta(debugName: "engine_stop_session", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiNetworkNetworkApproveTransmit({required String deviceId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkApproveTransmitConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkApproveTransmitConstMeta =>
      const TaskConstMeta(
        debugName: "network_approve_transmit",
        argNames: ["deviceId"],
      );

  @override
  void crateApiNetworkNetworkDenyTransmit({required String deviceId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkDenyTransmitConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkDenyTransmitConstMeta =>
      const TaskConstMeta(
        debugName: "network_deny_transmit",
        argNames: ["deviceId"],
      );

  @override
  void crateApiNetworkNetworkDjTransmit({required bool active}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(active, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkDjTransmitConstMeta,
        argValues: [active],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkDjTransmitConstMeta =>
      const TaskConstMeta(
        debugName: "network_dj_transmit",
        argNames: ["active"],
      );

  @override
  Stream<NetworkEventView> crateApiNetworkNetworkEvents() {
    final eventSink = RustStreamSink<NetworkEventView>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_network_event_view_Sse(eventSink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkEventsConstMeta,
        argValues: [eventSink],
        apiImpl: this,
      ),
    );
    return eventSink.stream;
  }

  TaskConstMeta get kCrateApiNetworkNetworkEventsConstMeta =>
      const TaskConstMeta(debugName: "network_events", argNames: ["eventSink"]);

  @override
  List<String> crateApiNetworkNetworkInputDevices() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkInputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkInputDevicesConstMeta =>
      const TaskConstMeta(debugName: "network_input_devices", argNames: []);

  @override
  MediaStatsView? crateApiNetworkNetworkMediaStats() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_media_stats_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkMediaStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkMediaStatsConstMeta =>
      const TaskConstMeta(debugName: "network_media_stats", argNames: []);

  @override
  void crateApiNetworkNetworkReleaseTransmit() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkReleaseTransmitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkReleaseTransmitConstMeta =>
      const TaskConstMeta(debugName: "network_release_transmit", argNames: []);

  @override
  void crateApiNetworkNetworkRequestTransmit() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkRequestTransmitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkRequestTransmitConstMeta =>
      const TaskConstMeta(debugName: "network_request_transmit", argNames: []);

  @override
  void crateApiNetworkNetworkRespondToCede({required bool cede}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(cede, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkRespondToCedeConstMeta,
        argValues: [cede],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkRespondToCedeConstMeta =>
      const TaskConstMeta(
        debugName: "network_respond_to_cede",
        argNames: ["cede"],
      );

  @override
  void crateApiNetworkNetworkStart({required String deviceName}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkNetworkStartConstMeta,
        argValues: [deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkStartConstMeta =>
      const TaskConstMeta(debugName: "network_start", argNames: ["deviceName"]);

  @override
  void crateApiNetworkNetworkStartCapture({String? deviceName}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(deviceName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkNetworkStartCaptureConstMeta,
        argValues: [deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkStartCaptureConstMeta =>
      const TaskConstMeta(
        debugName: "network_start_capture",
        argNames: ["deviceName"],
      );

  @override
  void crateApiNetworkNetworkStartWith({
    required String deviceName,
    required bool enableAudio,
    required bool dj,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceName, serializer);
          sse_encode_bool(enableAudio, serializer);
          sse_encode_bool(dj, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkNetworkStartWithConstMeta,
        argValues: [deviceName, enableAudio, dj],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkStartWithConstMeta =>
      const TaskConstMeta(
        debugName: "network_start_with",
        argNames: ["deviceName", "enableAudio", "dj"],
      );

  @override
  NetworkStatusView crateApiNetworkNetworkStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_status_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkStatusConstMeta =>
      const TaskConstMeta(debugName: "network_status", argNames: []);

  @override
  void crateApiNetworkNetworkStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkStopConstMeta =>
      const TaskConstMeta(debugName: "network_stop", argNames: []);

  @override
  void crateApiNetworkNetworkStopCapture() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkNetworkStopCaptureConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkStopCaptureConstMeta =>
      const TaskConstMeta(debugName: "network_stop_capture", argNames: []);

  @override
  void crateApiNetworkNetworkTransmitFile({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkNetworkTransmitFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNetworkTransmitFileConstMeta =>
      const TaskConstMeta(
        debugName: "network_transmit_file",
        argNames: ["path"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<NetworkEventView> dco_decode_StreamSink_network_event_view_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MediaStatsView dco_decode_box_autoadd_media_stats_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_media_stats_view(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MemberView> dco_decode_list_member_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_view).toList();
  }

  @protected
  List<PeerView> dco_decode_list_peer_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_view).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaStatsView dco_decode_media_stats_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return MediaStatsView(
      sessionActive: dco_decode_bool(arr[0]),
      isTransmitter: dco_decode_bool(arr[1]),
      mediaPort: dco_decode_u_16(arr[2]),
      receivedPackets: dco_decode_u_64(arr[3]),
      transmittedPackets: dco_decode_u_64(arr[4]),
      capturing: dco_decode_bool(arr[5]),
      clockSynced: dco_decode_bool(arr[6]),
      clockOffsetUs: dco_decode_i_64(arr[7]),
      clockRttUs: dco_decode_u_64(arr[8]),
      lastError: dco_decode_String(arr[9]),
      bufferedPackets: dco_decode_usize(arr[10]),
      bufferedUs: dco_decode_u_64(arr[11]),
    );
  }

  @protected
  MemberView dco_decode_member_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MemberView(
      deviceId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      addr: dco_decode_String(arr[2]),
      isTransmitter: dco_decode_bool(arr[3]),
      isMe: dco_decode_bool(arr[4]),
    );
  }

  @protected
  NetworkEventView dco_decode_network_event_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NetworkEventView(
      kind: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      deviceName: dco_decode_String(arr[2]),
      message: dco_decode_String(arr[3]),
    );
  }

  @protected
  NetworkStatusView dco_decode_network_status_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return NetworkStatusView(
      running: dco_decode_bool(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      deviceName: dco_decode_String(arr[2]),
      role: dco_decode_String(arr[3]),
      sessionId: dco_decode_String(arr[4]),
      coordinatorId: dco_decode_String(arr[5]),
      transmitterId: dco_decode_String(arr[6]),
      dj: dco_decode_bool(arr[7]),
      djTransmitters: dco_decode_list_String(arr[8]),
      members: dco_decode_list_member_view(arr[9]),
      peers: dco_decode_list_peer_view(arr[10]),
      pendingTransmitRequests: dco_decode_list_String(arr[11]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  MediaStatsView? dco_decode_opt_box_autoadd_media_stats_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_media_stats_view(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PeerView dco_decode_peer_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PeerView(
      deviceId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      addr: dco_decode_String(arr[2]),
      isCoordinator: dco_decode_bool(arr[3]),
    );
  }

  @protected
  SessionStatusView dco_decode_session_status_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SessionStatusView(
      active: dco_decode_bool(arr[0]),
      targetLatencyMs: dco_decode_u_64(arr[1]),
      sessionId: dco_decode_opt_box_autoadd_u_64(arr[2]),
      elapsedUs: dco_decode_opt_box_autoadd_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<NetworkEventView> sse_decode_StreamSink_network_event_view_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MediaStatsView sse_decode_box_autoadd_media_stats_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_media_stats_view(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberView> sse_decode_list_member_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerView> sse_decode_list_peer_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_view(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaStatsView sse_decode_media_stats_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionActive = sse_decode_bool(deserializer);
    var var_isTransmitter = sse_decode_bool(deserializer);
    var var_mediaPort = sse_decode_u_16(deserializer);
    var var_receivedPackets = sse_decode_u_64(deserializer);
    var var_transmittedPackets = sse_decode_u_64(deserializer);
    var var_capturing = sse_decode_bool(deserializer);
    var var_clockSynced = sse_decode_bool(deserializer);
    var var_clockOffsetUs = sse_decode_i_64(deserializer);
    var var_clockRttUs = sse_decode_u_64(deserializer);
    var var_lastError = sse_decode_String(deserializer);
    var var_bufferedPackets = sse_decode_usize(deserializer);
    var var_bufferedUs = sse_decode_u_64(deserializer);
    return MediaStatsView(
      sessionActive: var_sessionActive,
      isTransmitter: var_isTransmitter,
      mediaPort: var_mediaPort,
      receivedPackets: var_receivedPackets,
      transmittedPackets: var_transmittedPackets,
      capturing: var_capturing,
      clockSynced: var_clockSynced,
      clockOffsetUs: var_clockOffsetUs,
      clockRttUs: var_clockRttUs,
      lastError: var_lastError,
      bufferedPackets: var_bufferedPackets,
      bufferedUs: var_bufferedUs,
    );
  }

  @protected
  MemberView sse_decode_member_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_addr = sse_decode_String(deserializer);
    var var_isTransmitter = sse_decode_bool(deserializer);
    var var_isMe = sse_decode_bool(deserializer);
    return MemberView(
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      addr: var_addr,
      isTransmitter: var_isTransmitter,
      isMe: var_isMe,
    );
  }

  @protected
  NetworkEventView sse_decode_network_event_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return NetworkEventView(
      kind: var_kind,
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      message: var_message,
    );
  }

  @protected
  NetworkStatusView sse_decode_network_status_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_coordinatorId = sse_decode_String(deserializer);
    var var_transmitterId = sse_decode_String(deserializer);
    var var_dj = sse_decode_bool(deserializer);
    var var_djTransmitters = sse_decode_list_String(deserializer);
    var var_members = sse_decode_list_member_view(deserializer);
    var var_peers = sse_decode_list_peer_view(deserializer);
    var var_pendingTransmitRequests = sse_decode_list_String(deserializer);
    return NetworkStatusView(
      running: var_running,
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      role: var_role,
      sessionId: var_sessionId,
      coordinatorId: var_coordinatorId,
      transmitterId: var_transmitterId,
      dj: var_dj,
      djTransmitters: var_djTransmitters,
      members: var_members,
      peers: var_peers,
      pendingTransmitRequests: var_pendingTransmitRequests,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MediaStatsView? sse_decode_opt_box_autoadd_media_stats_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_media_stats_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerView sse_decode_peer_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_addr = sse_decode_String(deserializer);
    var var_isCoordinator = sse_decode_bool(deserializer);
    return PeerView(
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      addr: var_addr,
      isCoordinator: var_isCoordinator,
    );
  }

  @protected
  SessionStatusView sse_decode_session_status_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_active = sse_decode_bool(deserializer);
    var var_targetLatencyMs = sse_decode_u_64(deserializer);
    var var_sessionId = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_elapsedUs = sse_decode_opt_box_autoadd_u_64(deserializer);
    return SessionStatusView(
      active: var_active,
      targetLatencyMs: var_targetLatencyMs,
      sessionId: var_sessionId,
      elapsedUs: var_elapsedUs,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_network_event_view_Sse(
    RustStreamSink<NetworkEventView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_event_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_media_stats_view(
    MediaStatsView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_stats_view(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_view(
    List<MemberView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_view(
    List<PeerView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_stats_view(
    MediaStatsView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.sessionActive, serializer);
    sse_encode_bool(self.isTransmitter, serializer);
    sse_encode_u_16(self.mediaPort, serializer);
    sse_encode_u_64(self.receivedPackets, serializer);
    sse_encode_u_64(self.transmittedPackets, serializer);
    sse_encode_bool(self.capturing, serializer);
    sse_encode_bool(self.clockSynced, serializer);
    sse_encode_i_64(self.clockOffsetUs, serializer);
    sse_encode_u_64(self.clockRttUs, serializer);
    sse_encode_String(self.lastError, serializer);
    sse_encode_usize(self.bufferedPackets, serializer);
    sse_encode_u_64(self.bufferedUs, serializer);
  }

  @protected
  void sse_encode_member_view(MemberView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.addr, serializer);
    sse_encode_bool(self.isTransmitter, serializer);
    sse_encode_bool(self.isMe, serializer);
  }

  @protected
  void sse_encode_network_event_view(
    NetworkEventView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_network_status_view(
    NetworkStatusView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.coordinatorId, serializer);
    sse_encode_String(self.transmitterId, serializer);
    sse_encode_bool(self.dj, serializer);
    sse_encode_list_String(self.djTransmitters, serializer);
    sse_encode_list_member_view(self.members, serializer);
    sse_encode_list_peer_view(self.peers, serializer);
    sse_encode_list_String(self.pendingTransmitRequests, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_media_stats_view(
    MediaStatsView? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_media_stats_view(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_view(PeerView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.addr, serializer);
    sse_encode_bool(self.isCoordinator, serializer);
  }

  @protected
  void sse_encode_session_status_view(
    SessionStatusView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.active, serializer);
    sse_encode_u_64(self.targetLatencyMs, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sessionId, serializer);
    sse_encode_opt_box_autoadd_u_64(self.elapsedUs, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
