// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `empty_status`, `engine_ref`, `wire_event_callback`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

void networkStart({required String deviceName}) =>
    RustLib.instance.api.crateApiNetworkNetworkStart(deviceName: deviceName);

void networkStop() => RustLib.instance.api.crateApiNetworkNetworkStop();

NetworkStatusView networkStatus() =>
    RustLib.instance.api.crateApiNetworkNetworkStatus();

Stream<NetworkEventView> networkEvents() =>
    RustLib.instance.api.crateApiNetworkNetworkEvents();

void networkStartWith({
  required String deviceName,
  required bool enableAudio,
}) => RustLib.instance.api.crateApiNetworkNetworkStartWith(
  deviceName: deviceName,
  enableAudio: enableAudio,
);

MediaStatsView? networkMediaStats() =>
    RustLib.instance.api.crateApiNetworkNetworkMediaStats();

void networkTransmitFile({required String path}) =>
    RustLib.instance.api.crateApiNetworkNetworkTransmitFile(path: path);

void networkRequestTransmit() =>
    RustLib.instance.api.crateApiNetworkNetworkRequestTransmit();

void networkReleaseTransmit() =>
    RustLib.instance.api.crateApiNetworkNetworkReleaseTransmit();

void networkApproveTransmit({required String deviceId}) => RustLib.instance.api
    .crateApiNetworkNetworkApproveTransmit(deviceId: deviceId);

void networkDenyTransmit({required String deviceId}) =>
    RustLib.instance.api.crateApiNetworkNetworkDenyTransmit(deviceId: deviceId);

class MediaStatsView {
  final bool sessionActive;
  final bool isTransmitter;
  final int mediaPort;
  final BigInt receivedPackets;
  final BigInt transmittedPackets;
  final bool clockSynced;
  final PlatformInt64 clockOffsetUs;
  final BigInt clockRttUs;
  final String lastError;
  final BigInt bufferedPackets;
  final BigInt bufferedUs;

  const MediaStatsView({
    required this.sessionActive,
    required this.isTransmitter,
    required this.mediaPort,
    required this.receivedPackets,
    required this.transmittedPackets,
    required this.clockSynced,
    required this.clockOffsetUs,
    required this.clockRttUs,
    required this.lastError,
    required this.bufferedPackets,
    required this.bufferedUs,
  });

  @override
  int get hashCode =>
      sessionActive.hashCode ^
      isTransmitter.hashCode ^
      mediaPort.hashCode ^
      receivedPackets.hashCode ^
      transmittedPackets.hashCode ^
      clockSynced.hashCode ^
      clockOffsetUs.hashCode ^
      clockRttUs.hashCode ^
      lastError.hashCode ^
      bufferedPackets.hashCode ^
      bufferedUs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaStatsView &&
          runtimeType == other.runtimeType &&
          sessionActive == other.sessionActive &&
          isTransmitter == other.isTransmitter &&
          mediaPort == other.mediaPort &&
          receivedPackets == other.receivedPackets &&
          transmittedPackets == other.transmittedPackets &&
          clockSynced == other.clockSynced &&
          clockOffsetUs == other.clockOffsetUs &&
          clockRttUs == other.clockRttUs &&
          lastError == other.lastError &&
          bufferedPackets == other.bufferedPackets &&
          bufferedUs == other.bufferedUs;
}

class MemberView {
  final String deviceId;
  final String deviceName;
  final String addr;
  final bool isTransmitter;
  final bool isMe;

  const MemberView({
    required this.deviceId,
    required this.deviceName,
    required this.addr,
    required this.isTransmitter,
    required this.isMe,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      addr.hashCode ^
      isTransmitter.hashCode ^
      isMe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberView &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          addr == other.addr &&
          isTransmitter == other.isTransmitter &&
          isMe == other.isMe;
}

class NetworkEventView {
  final String kind;
  final String deviceId;
  final String deviceName;
  final String message;

  const NetworkEventView({
    required this.kind,
    required this.deviceId,
    required this.deviceName,
    required this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkEventView &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          message == other.message;
}

class NetworkStatusView {
  final bool running;
  final String deviceId;
  final String deviceName;
  final String role;
  final String sessionId;
  final String coordinatorId;
  final String transmitterId;
  final List<MemberView> members;
  final List<PeerView> peers;
  final List<String> pendingTransmitRequests;

  const NetworkStatusView({
    required this.running,
    required this.deviceId,
    required this.deviceName,
    required this.role,
    required this.sessionId,
    required this.coordinatorId,
    required this.transmitterId,
    required this.members,
    required this.peers,
    required this.pendingTransmitRequests,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      role.hashCode ^
      sessionId.hashCode ^
      coordinatorId.hashCode ^
      transmitterId.hashCode ^
      members.hashCode ^
      peers.hashCode ^
      pendingTransmitRequests.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkStatusView &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          role == other.role &&
          sessionId == other.sessionId &&
          coordinatorId == other.coordinatorId &&
          transmitterId == other.transmitterId &&
          members == other.members &&
          peers == other.peers &&
          pendingTransmitRequests == other.pendingTransmitRequests;
}

class PeerView {
  final String deviceId;
  final String deviceName;
  final String addr;
  final bool isCoordinator;

  const PeerView({
    required this.deviceId,
    required this.deviceName,
    required this.addr,
    required this.isCoordinator,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      addr.hashCode ^
      isCoordinator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerView &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          addr == other.addr &&
          isCoordinator == other.isCoordinator;
}
